FROM ubuntu:latest
RUN DEBIAN_FRONTEND=noninteractive apt-get update -y && apt-get upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install python3 -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install neovim -y
RUN DEBIAN_FRONTEND=noninteractive apt-get update
